# Generated by Django 4.2.5 on 2024-08-04 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artikel',
            fields=[
                ('id_artikel', models.AutoField(primary_key=True, serialize=False)),
                ('kode_artikel', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bahanbaku',
            fields=[
                ('id_bahanbaku', models.AutoField(primary_key=True, serialize=False)),
                ('nama_bahanbaku', models.CharField(max_length=100)),
                ('satuan', models.CharField(max_length=100)),
                ('safety_stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='spk',
            fields=[
                ('id_spk', models.AutoField(primary_key=True, serialize=False)),
                ('no_spk', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='transaksigudang',
            fields=[
                ('id_transaksigudang', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='konversi',
            fields=[
                ('id_konversi', models.AutoField(primary_key=True, serialize=False)),
                ('versi', models.DateField()),
                ('id_artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waktu.artikel')),
            ],
        ),
        migrations.CreateModel(
            name='detailtransaksigudang',
            fields=[
                ('id_detailtransaksigudang', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah', models.PositiveIntegerField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('keteranganacc', models.BooleanField(default=None, null=True)),
                ('id_bahanbaku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waktu.bahanbaku')),
                ('id_transaksigudang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waktu.transaksigudang')),
            ],
        ),
        migrations.CreateModel(
            name='detailspk',
            fields=[
                ('id_detailspk', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah', models.PositiveIntegerField()),
                ('id_artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waktu.artikel')),
                ('id_spk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waktu.spk')),
            ],
        ),
        migrations.CreateModel(
            name='detailkonversi',
            fields=[
                ('id_detailkonversi', models.AutoField(primary_key=True, serialize=False)),
                ('kuantitas', models.PositiveIntegerField()),
                ('id_bahanbaku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waktu.bahanbaku')),
                ('id_konversi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waktu.konversi')),
            ],
        ),
    ]
