# Generated by Django 4.2.5 on 2024-08-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waktu', '0002_alter_detailkonversi_kuantitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtransaksigudang',
            name='keteranganacc',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
