# Generated by Django 4.2.5 on 2024-08-05 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waktu', '0003_alter_detailtransaksigudang_keteranganacc'),
    ]

    operations = [
        migrations.CreateModel(
            name='suratjalanpembelian',
            fields=[
                ('id_sjp', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='detailsuratjalanpembelian',
            fields=[
                ('id_detailsjp', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah', models.PositiveIntegerField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('keteranganacc', models.BooleanField(default=False, null=True)),
                ('id_bahanbaku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waktu.bahanbaku')),
                ('id_sjp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waktu.suratjalanpembelian')),
            ],
        ),
    ]
