# Generated by Django 4.2.5 on 2024-08-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waktu', '0004_suratjalanpembelian_detailsuratjalanpembelian'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailspk',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
