# Generated by Django 4.2.5 on 2024-08-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waktu', '0005_detailspk_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailspk',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
